#server: 
#  port: 7080
#  tomcat: 
#    maxThreads: 1000
  
spring: 
  datasource: #数据源配置
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.182:3306/chnghx?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: mysql
 #freemarker 配置
  mvc: 
   view: 
    prefix: /templates/
    suffix: .ftl
#MQ
  rabbitmq: 
    host: 192.168.0.150
    port: 5672
    username: tong
    password: tong
    publisher-confirms: true
    virtual-host: /
    queues: queue
  redis: #### redis 配置
    database: 0 #Redis数据库索引（默认为0）
    host: 192.168.0.28 # Redis服务器地址
    password: 
    port: 6379
    timeout: 0 # 连接超时时间（毫秒）
    pool: 
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    